GameMarket/Components/SellerViewComponent.cs
using GameMarket.Models;
using GameMarket.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GameMarket.Components
{
    public class SellerViewComponent : ViewComponent
    {
        private readonly IOrderRepository _orderRepository;

        public SellerViewComponent(IOrderRepository orderRepository)
        {
            _orderRepository = orderRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            IEnumerable<Product> product = _orderRepository.GetSellerProduct();
            return View(product);
        }
    }
}

GameMarket/Controllers/StoreController.cs
using GameMarket.Models.Page;
using GameMarket.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GameMarket.Controllers
{
    public class StoreController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;

        public StoreController(IProductRepository productRepository, ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult Index([FromQuery(Name = "option")] QueryOption productOptions, QueryOption catOptions, int category)
        {
            ViewBag.Categories = _categoryRepository.GetCategories(catOptions);
            ViewBag.SelectedCategory = category;
            return View(_productRepository.GetProducts(productOptions, category));
        }
    }
}

GameMarket/Views/Store/Index.cshtml
@using GameMarket.Infrastructure;
@model PagedList<Product>

<div class="container-fluid">
    <div class="row">
        <div class="col-2">
            @Html.Partial("_Categories",ViewBag.Categories as PagedList<Category>)
        </div>
        
        <div class="col-10">
            <div class="container-fluid">
                <div class="row pt-1 pb-1 m-2">
                    <div class="col text-center">
                        @Html.Partial("_Page",Model)
                    </div>
                </div>
                <div class="row justify-content-center m-3">
                    <div class="col-1">
                        <input form="pageform" type="hidden" name="options.searchpropertyname" value="Name" />
                    </div>
                    <div class="col-4">
                        <input form="pageform" class="form-control" name="options.searchterm" placeholder="Поиск..." />
                    </div>
                    <div class="col-2">
                        <button form="pageform" class="btn btn-secondary" type="submit">Поиск</button>
                    </div>
                </div>
                    <vc:seller></vc:seller>

                @foreach (Product p in Model)
                {
                    <div class="row">
                        <div class="col">
                            <div class="car m-1 p-1 bg-light">
                                <div class="p-1">
                                    <h4>
                                        @p.Name
                                        <span style="float:right">
                                            <small>@p.RetailPrice</small>
                                        </span>
                                    </h4>
                                </div>
                                <form id="@p.Id" asp-action="AddToCart" asp-controller="Cart" method="post">
                                    <input type="hidden" name="Id" value="@p.Id" />
                                    <input type="hidden" name="Name" value="@p.Name" />
                                    <input type="hidden" name="RetailPrice" value="@p.RetailPrice" />
                                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                                    <span class="card-text p-1">
                                        @(p.Description ?? "Нет описание")
                                        <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">Добавить в корзину</button>
                                    </span>
                                </form>
                            </div>
                        </div>
                    </div>
                }
                
            </div>
        </div>
    </div>

</div>

GameMarket/Views/Store/_Categories.cshtml
@model PagedList<Category>

<div class="container-fluid mt-4">
    <div class="row no-gutters">
        <div class="col mt-1">
            <button form="pageform" name="category" value="0" type="submit" class="btn btn-group @(ViewBag.SelectedCategory == 0?"btn-primary":"btn-outline-primary")">Все</button>
        </div>
    </div>

    <div class="row no-gutters mt-4"></div>
    <div class="row no-gutters">
        <div class="col mt-1">
            <button form="pageform" name="catoptions.currentPage" value="@(Model.CurrentPage-1)" class="btn btn-group btn-outline-secondary @(Model.HasPreviousPage?"":"disabled")" type="submit">Назад</button>
        </div>
    </div>
    @foreach (Category c in Model)
    {
        <div class="row no-gutters">
            <div class="col mt-1">
                <button form="pageform" name="category" value="@c.Id" type="submit" class="btn blockquote @(ViewBag.SelectedCategory == c.Id?"btn-primary":"btn-outline-primary")">
                    @c.Name
                </button>
            </div>
        </div>
    }
    <div class="row no-gutters">
        <div class="col mt-1">
            <button form="pageform" name="catoptions.currentPage" value="@(Model.CurrentPage+1)" class="btn btn-group btn-outline-secondary @(Model.HasNextPage?"":"disabled")" type="submit">Назад</button>
        </div>
    </div>
</div>

GameMarket/Views/Store/_Layout.cshtml
@using GameMarket.Infrastructure;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameStore.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container-fluid">
        <div class="row bg-dark p-4 text-white">
            <div class="col-auto"><h4>Магазин Игр</h4></div>
            <div class="col"><a asp-action="Index" asp-controller="Home" class="text-decoration-none text-white p-4">Главная</a></div>
            <div class="col-auto text-end">
                @await Component.InvokeAsync("Cart",Context.Session)
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GameStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>