GameMarket/Components/NewProductsViewComponent.cs
using GameMarket.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GameMarket.Components
{
    public class NewProductsViewComponent:ViewComponent
    {
        private readonly IProductRepository _repository;

        public NewProductsViewComponent(IProductRepository repository)
        {
            _repository = repository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(_repository.GetNewProducts());
        }
    }
}

GameMarket/Controllers/ArticleController.cs
using GameMarket.Models;
using GameMarket.Models.Page;
using GameMarket.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GameMarket.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleRepository _articleRepository;

        public ArticleController(IArticleRepository articleRepository)
        {
            _articleRepository = articleRepository;
        }

        public IActionResult Index(QueryOption option)
        {
            ViewBag.Title = "Все статьи";
            return View(_articleRepository.GetAll(option));
        }
        public IActionResult Detail(int id)
        {
            ViewBag.Title = "Подробнее";
            return View(_articleRepository.GetArticle(id));
        }
        [HttpGet]
        public IActionResult AddOrUpdate(int id)
        {
            ViewBag.Title = id == 0 ? "Добавить" : "Редактировать";
            if (id == 0)
            {
                return View(new Article());
            }
            return View(_articleRepository.GetArticle(id));
        }
        [HttpPost]
        public IActionResult AddOrUpdate(Article article)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Title = article.Id == 0 ? "Добавить" : "Редактировать";
                return View(article);
            }
            if (article.Id == 0)
            {
                _articleRepository.AddArticle(article);
            }
            else
            {
                _articleRepository.UpdateArticle(article);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

GameMarket/Controllers/HomeController.cs
using GameMarket.Models;
using GameMarket.Models.Page;
using GameMarket.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GameMarket.Controllers
{
    public class HomeController : Controller
    {
        private readonly IArticleRepository _articleRepository;

        public HomeController(IArticleRepository articleRepository)
        {
            _articleRepository = articleRepository;
        }

        public IActionResult Index(QueryOption option)
        {
            ViewBag.Title = "Главная страница";
            return View(_articleRepository.GetAll(option));
        }
    }
}

GameMarket/Views/Home/Index.cshtml
@{
    ViewData["Title"] = ViewBag.Title;
}

@model PagedList<Article>

<div class="text-center">
    <h3 class="h3">@ViewBag.Title</h3>
    <div>
        <vc:new-products></vc:new-products>
    </div>

    <h3 class="h3">Все статьи</h3>
    <div class="row row-cols-4">
        @foreach (Article article in Model)
        {
            <div class="col">
                <div class="card m-3" style="width: 18rem;height:22rem">
                    <img src="@article.ImageUrl" class="card-img-top" alt="image">
                    <div class="card-body">
                        <h5 class="card-title">@article.Title</h5>
                        <p class="card-text">@article.EditTime.ToShortDateString()</p>
                        <a asp-action="Detail" asp-controller="Article" asp-route-id="@article.Id" class="btn btn-primary">Подробнее</a>
                    </div>
                </div>
            </div>

        }
    </div>
    @Html.Partial("_Page",Model)
</div>