GameMarket/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace GameMarket.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Title = "Админ страница";
            return View();
        }
    }
}

GameMarket/Controllers/StoreController.cs
using GameMarket.Models.Page;
using GameMarket.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GameMarket.Controllers
{
    public class StoreController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;

        public StoreController(IProductRepository productRepository, ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult Index([FromQuery(Name = "option")] QueryOption productOptions, QueryOption catOptions, int category)
        {
            ViewBag.Categories = _categoryRepository.GetCategories(catOptions);
            ViewBag.SelectedCategory = category;
            return View(_productRepository.GetProducts(productOptions, category));
        }
    }
}

GameMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameMarket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameMarket.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GameMarket</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Магазин</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GameMarket - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GameMarket/Views/Shared/_Page.cshtml
<form id="pageform">
        <nav aria-label="Page navigation example">
            <ul class="pagination pagination-sm justify-content-center">
                <li class="page-item @(!Model.HasPreviousPage ? "disabled":"")">
                    <button name="option.CurrentPage" value="@(Model.CurrentPage-1)" class="page-link" type="submit">Previous</button>
                </li>

                @if (Model.CurrentPage>1)
                {
                    @for (int i = Model.CurrentPage-1; i < Model.CurrentPage; i++)
                    {
                        <li class="page-item">
                            <button name="option.CurrentPage" value="@i" class="page-link" type="submit">@i</button>
                        </li>
                    }                    
                }
                <li class="page-item active"><a class="page-link" href="#">@Model.CurrentPage</a></li>

                @if (Model.CurrentPage < Model.TotalPage-1)
                {
                    <li class="page-item">
                        <button name="option.CurrentPage" value="@(Model.CurrentPage+1)" class="page-link" type="submit">@(Model.CurrentPage + 1)</button>
                    </li>
                }
               

                @if (Model.CurrentPage < Model.TotalPage && Model.TotalPage > 2)
                {
                    <li class="page-item">
                        ...
                    </li>
                    @for (int i = Model.TotalPage; i < Model.TotalPage+1; i++)
                    {
                       
                        <li class="page-item">
                            <button name="option.CurrentPage" value="@i" class="page-link" type="submit">@i</button>
                        </li>
                    }
                }

                <li class="page-item @(!Model.HasNextPage ? "disabled":"")">
                    <button name="option.CurrentPage" value="@(Model.CurrentPage+1)" class="page-link" type="submit">Next</button>
                </li>

                <li class="page-item">
                    <select name="option.PageSize" class="form-select-sm">
                    @foreach (int pagesize in new[] {5,10,20,50,100 })
                    {
                        <option value="@pagesize" selected="@(Model.PageSize == pagesize)">@pagesize</option>
                    }
                    </select>
                </li>
                <li class="page-item">
                    <button name="option.CurrentPage" value="1" class="btn btn-primary btn-sm" type="submit">Изменить колчиества элеменотов</button>
                </li>
            </ul>
        </nav>
    </form>

GameMarket/Views/Shared/_PageOption.cshtml
@{
    ViewBag.Seaches = new string[] { "Name", "Category.Name" };
    ViewBag.Sort = new string[] { "Name", "Category.Name", "PurchasePrice", "RetailPrice" };
}
<div class="row justify-content-end m-2">
    <label class="col-1">Поиск</label>
    <div class="col-3">
        <select form="pageform" name="option.SearchPropertyName" class="form-select">
            @foreach (string s in ViewBag.Seaches)
            {
                <option value="@s" selected="@(Model.Options.SearchPropertyName == s)">
                    @(s.IndexOf('.') == -1 ? s : s.Substring(0, s.IndexOf('.')))
                </option>
            }
        </select>
    </div>
    <div class="col-3">
        <input form="pageform" class="form-control" name="option.SearchTerm" value="@Model.Options.SearchTerm" />
    </div>
    <button form="pageform" class="col-1 btn btn-secondary btn-sm">Поиск</button>
</div>


<div class="row justify-content-end m-2">
    <label class="col-1 form-label">Сортировка</label>
    <div class="col-3">
        <select class="form-select" form="pageform" name="order.OrderPropertyName">
            @foreach (string sort in ViewBag.Sort)
            {
                <option value="@sort" selected="@(Model.Options.OrderPropertyName == sort)">
                    @(sort.IndexOf('.') == -1 ? sort : sort.Substring(0, sort.IndexOf('.')))
                </option>
            }
        </select>
    </div>
    <div class="col-3">
        <input form="pageform" type="checkbox" name="option.DescendingOrder" id="options.DescendingOrder" class="form-check-input"
               value="true" checked="@Model.Options.DescendingOrder" />
        <label class="form-check-label">Сортировка по убыванию</label>
    </div>
    <div class="col-1 text-right">
        <button form="pageform" class="btn btn-secondary" type="submit">Сортировка</button>
    </div>
</div>