GameMarket/Controllers/ArticleController.cs
using GameMarket.Models;
using GameMarket.Models.Page;
using GameMarket.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GameMarket.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleRepository _articleRepository;

        public ArticleController(IArticleRepository articleRepository)
        {
            _articleRepository = articleRepository;
        }

        public IActionResult Index(QueryOption option)
        {
            ViewBag.Title = "Все статьи";
            return View(_articleRepository.GetAll(option));
        }
        public IActionResult Detail(int id)
        {
            ViewBag.Title = "Подробнее";
            return View(_articleRepository.GetArticle(id));
        }
        [HttpGet]
        public IActionResult AddOrUpdate(int id)
        {
            ViewBag.Title = id == 0 ? "Добавить" : "Редактировать";
            if (id == 0)
            {
                return View(new Article());
            }
            return View(_articleRepository.GetArticle(id));
        }
        [HttpPost]
        public IActionResult AddOrUpdate(Article article)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Title = article.Id == 0 ? "Добавить" : "Редактировать";
                return View(article);
            }
            if (article.Id == 0)
            {
                _articleRepository.AddArticle(article);
            }
            else
            {
                _articleRepository.UpdateArticle(article);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

GameMarket/Controllers/OrderController.cs
using GameMarket.Models;
using GameMarket.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GameMarket.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly IProductRepository _productRepository;

        public OrderController(IOrderRepository orderRepository, IProductRepository productRepository)
        {
            _orderRepository = orderRepository;
            _productRepository = productRepository;
        }

        public IActionResult Index()
        {
            ViewBag.Title = "Все заказы";
            return View(_orderRepository.GetOrders());
        }
        public IActionResult AddOrUpdate(int id)
        {
            var product = _productRepository.GetAllProducts();
            ViewBag.Title = id == 0 ? "Добвавление заказа" : "Редактирование заказа";
            Order order = id == 0 ? new Order() : _orderRepository.GetById(id);
            IDictionary<int, OrderLines> lineMaps = order.OrderLines?.ToDictionary(l => l.ProductId) ?? new Dictionary<int, OrderLines>();

            ViewBag.Lines = product.Select(p => lineMaps.ContainsKey(p.Id) ? lineMaps[p.Id] : new OrderLines()
            {
                Product = p,
                ProductId = p.Id,
                Quantity = 0
            });
            return View(order);
        }
        [HttpPost]
        public IActionResult AddOrUpdate(Order order)
        {
            //ViewBag.Title = order.Id == 0 ? "Добвавление заказа" : "Редактирование заказа";
            //if (!ModelState.IsValid)
            //{
            //    return View(order);
            //}
            if (order.Id == 0)
            {
                _orderRepository.AddOrder(order);
            }
            else
            {
                _orderRepository.UpdateOrder(order);
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult Delete(Order order)
        {
            _orderRepository.DeleteOrder(order);
            return RedirectToAction(nameof(Index));
        }
    }
}

GameMarket/Controllers/ProductController.cs
using GameMarket.Models;
using GameMarket.Models.Page;
using GameMarket.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GameMarket.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;

        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult Index(QueryOption option)
        {
            ViewBag.Title = "Все товары";
            return View(_productRepository.GetProducts(option));
        }

        public IActionResult AddOrUpdate(int id)
        {
            ViewBag.Title = id == 0 ? "Добавление товара" : "Редактирование товара";
            ViewBag.Categories = _categoryRepository.GetAllCategories();

            if (id == 0)
            {

                return View(new Product());
            }
            return View(_productRepository.GetById(id));
        }

        [HttpPost]
        public IActionResult AddOrUpdate(Product product)
        {
            ViewBag.Title = product.Id == 0 ? "Добавление товара" : "Редактирование товара";
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = _categoryRepository.GetAllCategories();
                return View(product);
            }
            if (product.Id == 0)
            {
                _productRepository.AddProduct(product);
            }
            else
            {
                _productRepository.UpdateProduct(product);
            }
            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        public IActionResult Delete(Product product)
        {
            _productRepository.RemoveProduct(product);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Detail(int id)
        {
            ViewBag.Title = "Детали товара";
            return View(_productRepository.GetById(id));
        }
    }
}

GameMarket/Controllers/StoreController.cs
using GameMarket.Models.Page;
using GameMarket.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GameMarket.Controllers
{
    public class StoreController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;

        public StoreController(IProductRepository productRepository, ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult Index([FromQuery(Name = "option")] QueryOption productOptions, QueryOption catOptions, int category)
        {
            ViewBag.Categories = _categoryRepository.GetCategories(catOptions);
            ViewBag.SelectedCategory = category;
            return View(_productRepository.GetProducts(productOptions, category));
        }
    }
}

GameMarket/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = ViewBag.Title;
}


<h4 class="h4 text-center">@ViewBag.Title</h4>

GameMarket/Views/Admin/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameMarket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameMarket.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GameMarket</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Продукты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Категории</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Статьи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Заказы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Магазин</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GameMarket - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>